stop immediately if label is missing

diff --git a/.github/workflows/auto-pkg-maintenance.yaml b/.github/workflows/auto-pkg-maintenance.yaml
--- a/.github/workflows/auto-pkg-maintenance.yaml
+++ b/.github/workflows/auto-pkg-maintenance.yaml
@@ -38,6 +38,13 @@ jobs:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
+      - name: Test for auto-pkg-maintenance label
+        if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'auto-pkg-maintenance')
+        shell: bash
+        run: |
+          echo "::error::Manual approval by the repository owner is required to enable automatic package maintenance on this PR."
+          exit 1
+
       - uses: actions/checkout@v2
 
         # Make sure the PR branch is checked out for pull requests
@@ -46,13 +53,6 @@ jobs:
         uses: r-lib/actions/pr-fetch@v2
         with:
           repo-token: ${{ github.token }}
-
-      - name: Test for auto-pkg-maintenance label
-        if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'auto-pkg-maintenance')
-        shell: bash
-        run: |
-          echo "::error::Manual approval by the repository owner is required to enable automatic package maintenance on this PR."
-          exit 1
 
       - uses: r-lib/actions/setup-r@v2
         with:
